### PR TITLE
Fixed createdAt and updatedAt Conflicts For Admin Updates

### PR DESCRIPTION
**Pull request by subhankar-panda**

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Why do you need to delete these fields? I believe they should be updated by a "onUpdate" handler from within the plugins themselves?

**Comment by subhankar-panda** [comment]
I thought so too, but if `req.body` has an `updatedAt` or `createdAt` property in it, we run into this error 

image

This is probably a library bug, and it doesn't seem like mongoose-update is maintained anymore. Might be time to move to [this](http://mongoosejs.com/docs/guide.html#timestamps)

**Comment by RedbackThomson** [comment]
Oh it's built in now? Awesome yeah lets totally try to move to that.

**Comment by RedbackThomson** [comment]
Remove the package from the packages.json just in case

**Pull request merged**
